import {
  bird_1,
  bird_2,
  bird_3,
  bird_4,
  cat_1,
  cat_2,
  cat_3,
  cat_4,
  cat_5,
  dog_1,
  dog_2,
  dog_3,
  dog_4,
  dog_5,
  dog_6,
  dog_7,
  dog_8,
  dog_9,
  dog_10,
} from "../assets/Images";


export const adoptData = [
  {
    id: "656429",
    name: "Kylah",
    age: "2 Years",
    image: dog_1,
    gender: "Female",
    breed: "American Eskimo",
    Category: "Dog",
  },
  {
    id: "656431",
    name: "Bella",
    age: "3 Years",
    image: dog_2,
    gender: "Female",
    breed: "Lhasa Apso",
    Category: "Dog",
  },
  {
    id: "656430",
    name: "Spotty",
    age: "8 Months",
    image: dog_3,
    gender: "Female",
    breed: "Maine Coon",
    Category: "Cat",
  },
  {
    id: "656443",
    name: "Slopy",
    age: "8 Months",
    image: cat_4,
    gender: "Female",
    breed: "Maine Coon",
    Category: "Cat",
  },
  {
    id: "656447",
    name: "Moon",
    age: "3 Months",
    image: bird_3,
    gender: "Female",
    breed: "Finch",
    Category: "Bird",
  },
  {
    id: "656445",
    name: "Sky",
    age: "3 Months",
    image: bird_2,
    gender: "Female",
    breed: "Budie",
    Category: "Bird",
  },
  {
    id: "656444",
    name: "Shawty",
    age: "8 Months",
    image: cat_5,
    gender: "Male",
    breed: "Birman",
    Category: "Cat",
  },
  {
    id: "656446",
    name: "Blue",
    age: "5 Months",
    image: bird_1,
    gender: "Male",
    breed: "Budie",
    Category: "Bird",
  },
  {
    id: "656433",
    name: "Letty",
    age: "1 Year",
    image: dog_4,
    gender: "Female",
    breed: "Maltese",
    Category: "Dog",
  },
  {
    id: "656434",
    name: "Luna",
    age: "4 Years",
    image: dog_5,
    gender: "Male",
    breed: "Golden Retriever",
    Category: "Dog",
  },
  {
    id: "656435",
    name: "Ranger",
    age: "4 Years",
    image: dog_6,
    gender: "Male",
    breed: "German Shepard",
    Category: "Dog",
  },
  {
    id: "656436",
    name: "Tommy",
    age: "4 Years",
    image: dog_7,
    gender: "Male",
    breed: "Caucasian",
    Category: "Dog",
  },
  {
    id: "656437",
    name: "Zee",
    age: "1.5 Years",
    image: dog_8,
    gender: "Male",
    breed: "Serbarian Huskie",
    Category: "Dog",
  },
  {
    id: "656437",
    name: "Gentle",
    age: "4 Years",
    image: dog_8,
    gender: "Male",
    breed: "Pitbull",
    Category: "Dog",
  },
  {
    id: "656438",
    name: "Kendra",
    age: "4 Years",
    image: dog_9,
    gender: "Female",
    breed: "Frenchie",
    Category: "Dog",
  },
  {
    id: "656439",
    name: "Marbel",
    age: "6 Years",
    image: dog_10,
    gender: "Male",
    breed: "Rottweiler",
    Category: "Dog",
  },
  {
    id: "656440",
    name: "Harley",
    age: "4 Years",
    image: cat_1,
    gender: "Male",
    breed: "Persian",
    Category: "Cat",
  },
  {
    id: "656441",
    name: "Shawty",
    age: "8 Months",
    image: cat_2,
    gender: "Female",
    breed: "Birman",
    Category: "Cat",
  },
  {
    id: "656442",
    name: "Kia",
    age: "2 Months",
    image: cat_3,
    gender: "Female",
    breed: "Abyssinian",
    Category: "Cat",
  },
  {
    id: "656445",
    name: "Sky",
    age: "2 Months",
    image: bird_4,
    gender: "Female",
    breed: "Cockatiel",
    Category: "Bird",
  },
];


/* 
    adoptData.slice(0, 8).map(adopt => ())
*/