import { FaCheck, FaMedkit, FaShieldAlt } from "react-icons/fa";
import {
  petsitter1,
  petsitter2,
  petsitter3,
  petsitter4,
  petsitter5,
  groomer1,
  groomer2,
  groomer3,
  groomer4,
  groomer5,
  vet1,
  vet2,
  vet3,
  vet4,
  vet5,
  vet6,
  vet7,
  
} from "../assets/Images";
import { FaCertificate } from "react-icons/fa6";

export const personnelsData = [
  {
    id: "656429",
    name: "Kylah",
    exp: "2 Years",
    image: vet1,
    location: "Lagos, Ng",
    Category: "Veterinary",
  },
  {
    id: "656431",
    name: "Bella",
    exp: "3 Years",
    image: vet2,
    location: "Abuja, Ng",
    Category: "Veterinary",
  },
  {
    id: "656430",
    name: "Spotty",
    exp: "8 Months",
    image: vet3,
    location: "Abuja, Ng",
    Category: "Veterinary",
  },
  {
    id: "656443",
    name: "Slopy",
    exp: "8 Months",
    image: groomer4,
    location: "P.Harcourt, Ng",
    Category: "Pet Groomer",
  },
  {
    id: "656447",
    name: "Moon",
    exp: "3 Months",
    image: petsitter3,
    location: "Kaduna, Ng",
    Category: "Pet Sitter",
  },
  {
    id: "656445",
    name: "Sky",
    exp: "3 Months",
    image: petsitter2,
    location: "Lagos, Ng",
    Category: "Pet Sitter",
  },
  {
    id: "656444",
    name: "Shawty",
    exp: "8 Months",
    image: groomer5,
    location: "Enugu, Ng",
    Category: "Pet Groomer",
  },
  {
    id: "656446",
    name: "Blue",
    exp: "5 Months",
    image: petsitter1,
    location: "Owerri, Ng",
    Category: "Pet Sitter",
  },
  {
    id: "656433",
    name: "Letty",
    exp: "1 Year",
    image: vet4,
    location: "Enugu, Ng",
    Category: "Veterinary",
  },
  {
    id: "656434",
    name: "Luna",
    exp: "4 Years",
    image: vet5,
    location: "A. Ibom, Ng",
    Category: "Veterinary",
  },
  {
    id: "656435",
    name: "Ranger",
    exp: "4 Years",
    image: vet6,
    location: "Abuja, Ng",
    Category: "Veterinary",
  },
  {
    id: "656436",
    name: "Tommy",
    exp: "4 Years",
    image: vet7,
    location: "Lagos, Ng",
    Category: "Veterinary",
  },
  {
    id: "656437",
    name: "Zee",
    exp: "1.5 Years",
    image: petsitter5,
    location: "Enugu, Ng",
    Category: "Pet Sitter",
  },
  {
    id: "656440",
    name: "Harley",
    exp: "4 Years",
    image: groomer1,
    location: "Kaduna, Ng",
    Category: "Pet Groomer",
  },
  {
    id: "656441",
    name: "Shawty",
    exp: "8 Months",
    image: groomer2,
    location: "Owerri, Ng",
    Category: "Pet Groomer",
  },
  {
    id: "656442",
    name: "Kia",
    exp: "2 Months",
    image: groomer3,
    location: "Kaduna, Ng",
    Category: "Pet Groomer",
  },
  {
    id: "656446",
    name: "Sky",
    exp: "2 Months",
    image: petsitter4,
    location: "Anambra, Ng",
    Category: "Pet Sitter",
  },
];

export const aside = [
  {
    id: "656430",
    icon: <FaCheck className="text-green-700"/>,
    name: "Background Check Passed",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat dolorem repellat maxime",
  },
  {
    id: "656431",
    icon: <FaCertificate className="text-red-700"/>,
    name: "Certified Pet Sitter",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat dolorem repellat maxime",
  },
  {
    id: "656433",
    icon: <FaMedkit className="text-white"/>,
    name: "Pet First Aid Trained",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat dolorem repellat maxime",
  },
  {
    id: "656432",
    icon: <FaShieldAlt className="text-gray-600"/>,
    name: "Pet First Aid Trained",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat dolorem repellat maxime",
  },
];